# Generated by Django 4.2 on 2023-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('about_me', models.TextField()),
                ('objective', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=300)),
                ('my_image', models.ImageField(upload_to='allpic')),
            ],
        ),
    ]
