# Generated by Django 4.2 on 2023-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
