# Generated by Django 4.2 on 2023-05-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_experience_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degee_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('start_dt', models.DateField(blank=True)),
                ('end_dt', models.DateField(blank=True)),
                ('gpa', models.CharField(max_length=50)),
                ('imgs', models.ImageField(blank=True, upload_to='certificates')),
            ],
        ),
    ]
