# Generated by Django 4.2 on 2023-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_educations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
