# Generated by Django 4.2 on 2023-05-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_educations_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='educations',
            name='cert_imgs',
            field=models.ImageField(blank=True, null=True, upload_to='certifications'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='school'),
        ),
    ]
