# Generated by Django 4.2 on 2023-05-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_range',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
