# Generated by Django 4.2 on 2023-05-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='email',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='references',
            name='positions',
            field=models.CharField(max_length=150),
        ),
    ]
