# Generated by Django 4.2 on 2023-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_skills_port_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('portfile', models.FileField(blank=True, upload_to='portfoliofile')),
                ('portimg', models.ImageField(blank=True, upload_to='portimg')),
            ],
        ),
    ]
